#+TITLE:Introduction
#+AUTHOR: Pim


* Table Of Contents :toc:
- [[#propositions][Propositions]]
  - [[#quest-quune-proposition-][Qu'est qu'une proposition ?]]
  - [[#exemples][Exemples]]
  - [[#subtilités][Subtilités]]
  - [[#les-propositions-composées][Les propositions composées]]
- [[#propositions-avec-symboles][Propositions avec symboles]]
  - [[#conjonction][Conjonction]]
  - [[#disjonction][Disjonction]]
  - [[#implication][Implication]]
  - [[#léquivalence][L'équivalence]]
  - [[#négation][Négation]]
  - [[#exercice-complexe-safépeur][Exercice complexe (safépeur)]]
- [[#les-quantifiers][Les Quantifiers]]
  - [[#quest-quun-quantifier-][Qu'est qu'un quantifier ?]]
  - [[#les-règles-des-quantifiers][Les règles des quantifiers]]
  - [[#exercices][Exercices]]

* Propositions
** Qu'est qu'une proposition ?

Une proposition est *un objet théorique*, ayant la particularité suivante : *il est soit Vrai, soit Faux*.

** Exemples

- John a 27 ans.

Correcte et simple.

- Il fait beau aujourd'hui.

Correcte et facilement vérifiable.

- 4 > 9
Malgrès une absurdité, cela n'en reste pas moins une proposition. (mais ca pique les yeux quand même).

** Subtilités

- Une proposition qui ne décrit qu'une seule idée (1 = 2 - 1) est dit *atomique*

- Les prochaines phrases, informations *ne sont pas des propositions*:

  + Va t'en.

    N'a pas de sens. Ne donne pas d'idée, c'est juste un ordre. (mais reste quand même hein)

  + x - 3 = 5

    Pas correct, car nous n'avons *pas d'informations sur x*. Il faut lui attribuer une valeur pour que cela devienne une proposition.

  + Cette proposition est fausse.

    Une proposition ne peut pas se *réferrer à elle-même*.

** Les propositions composées

A l'instar des propositions atomiques (une seule idée), les *compositions composées* sont composées de plusieurs sous propositions. Nous avons donc avoir besoin *d'objet nous permettant de lier les propositions entre-elles*. (je les decrirai dans le prochain sujet)

- Exemple:

  *John a 27 ans et il aime les bières*

  Ici 2 idées misent en évidence, et misent en relation avec *et*

* Propositions avec symboles

** Conjonction

Une proposition composée avec une conjonction nécessite que les *2 sous-propositions soit vraies*.
On le note \land .

*** Exemples:

  - (5 > 3) \land (9 < 10)

    Vrai, *car les deux sous-propositions sont vraies*

  - (5 < 3) \land (9 < 10)

    Faux, car 5 < 3 est faux

  - ((5 > 3) \land (9 < 10)) \land John est heureux

    John étant quelqu'un d'heureux, cette proposition est vraie.

*** Sa table de vérité

| A | B | A \land B |
|---+---+-----------|
| 0 | 0 |         0 |
| 0 | 1 |         0 |
| 1 | 0 |         0 |
| 1 | 1 |         1 |

Les *1* représentent une proposition vraie, les *0* des fausses.


** Disjonction

Cette fois-ci, il faut que *au moins une des deux sous-proposition soit vraie*. On la note \lor .

*** Exemples:

  - (5 > 3) \lor (5 < 3)

    Vrai, c'est la première sous-proposition qui prend le dessus.

  - (10 > 15) \lor (8 < 5)

    Faux.

  - ((John est heureux) \lor (John est malheureux)) \lor (2/3 = 3/2)

    Vraie, la puissance de la gaieté de John est absolue !

*** Sa table de vérité

| A | B | A \lor B |
|---+---+----------|
| 0 | 0 |        0 |
| 0 | 1 |        1 |
| 1 | 0 |        1 |
| 1 | 1 |        1 |

** Implication
L'implication peut-être lu comme un *si ... alors*. On la note \Rightarrow .Dans l'expression
*A \Rightarrow B*, si A est vraie, alors le résultat sera *B*, sinon Vraie.

*** Exemples
- (3 < 2) \Rightarrow (5 < 3)

Vrai, car la proposition initiale (le A dans le pattern juste au dessus), est faux, donc le résultat sera vraie.

- (2 = 1 + 1) \Rightarrow (John est triste)

Bien sur, comme John est heureux, le résultat est Faux

*** Sa table de vérité

| A | B | A \Rightarrow B |
|---+---+-----------------|
| 0 | 0 |        1        |
| 0 | 1 |        1        |
| 1 | 0 |        0        |
| 1 | 1 |        1        |



** L'équivalence

Comme son nom l'indique, cela correspond à vérifier si les deux sous-propositions sont équivalentes. On la note \Leftrightarrow

*** Exemples

- ((3 < 5) \land (9 < 5)) \Leftrightarrow ((4 = 8/2) \Rightarrow (3 > 4))

Les *deux sous-propositions étant fausses*, la proposition est donc vraie (si vous avez un doute sur pourquoi ces sous-propositions sont fausses, relisez les paragraphes qui leurs sont dédiés)

- x est positif \Leftrightarrow x est négatif

Les deux sous-propositions étant contraires (on va le voir juste après), il y a donc *nécessairement une des deux qui est fausse, et l'autre vraie* (inutile de connaître x). Ainsi le résultat sera faux.

*** Sa table de vérité

| A | B | A \Leftrightarrow B |
|---+---+---------------------|
| 0 | 0 |                   1 |
| 0 | 1 |                   0 |
| 1 | 0 |                   0 |
| 1 | 1 |                   1 |

** Négation

La négation est assez simple, elle change simplement l'état d'une proposition. On la note \neg


*** Exemples

- \neg ((3 < 4) \Leftrightarrow (4 < 3))

  Vrai, la proposition est fausse initialement, ainsi son état passe à vraie.

- \neg ((100 = 10 * 10) \Rightarrow ((3 \in S) \land (3 \notin S)))

  Vrai aussi


*** Sa table de vérité

| A | \neg A |
|---+--------|
| 0 |      1 |
| 1 |      0 |


** Exercice complexe (safépeur)

Essaye de les faire sans regarder la réponse, mais bon tu fais ce que tu veux.

*** Exercice

Posons T comme étant une proposition à l'état vraie.

Determinez pour chacun des cas suivant, si on peut connaître à coup sur le résultat de la proposition. (Un exemple pour exprimer mon propos)

- Exemple :

  T \land (\neg T)

  Ici, nous pouvons être à coup sur que le résultat sera faux. C'est cette certitude que nous cherchons. Il suffit de dire si elle existe ou non, si oui, donnez sa valeur.

1) T \lor A
2) T \Rightarrow A
3) \neg T \Rightarrow \neg (A \lor B)
4) \neg (\neg T \land A) \Leftrightarrow \neg T
5) \neg ((\neg T \land \neg A) \Leftrightarrow \neg B)
6) A \Rightarrow (\neg B \Rightarrow (\neg T \Rightarrow \neg A))

*** Solutions

1) T étant vrai, pas besoin de savoir l'état de A pour savoir que le résultat est déjà défini, et est vrai.
2) On ne peut pas savoir, la solution dépend de A.
3) On peut le determiner, nous somme dans le cas contraire du précedant, la première proposition étant fausse, le résultat est fini, qu'importe la deuxième. Le résultat est donc vrai.

   (Jusque là c'était juste de la lecture des tables de vérités)

4) Procédons au cas par cas

   - (\neg T \land A) : Faux car \neg T est faux
   - \neg (\neg T \land A) : Vrai, par déduction de l'affirmation précedente
   - \neg (\neg T \land A) \Leftrightarrow \neg T : Faux, car \neg T et Vrai ne sont pas identiques.

5) Procédons au cas par cas

   - (\neg T \land \neg A) : Faux, car \neg T est Faux
   - (\neg T \land \neg A) \Leftrightarrow \neg B) : On ne peut pas savoir, nous ne connaissons rien de B
   - \neg ((\neg T \land \neg A) \Leftrightarrow \neg B) : Ainsi on ne peut pas le déterminer.

6) Procédons au cas par cas

   - \neg T \Rightarrow \neg A Necessairement vrai, \neg T est faux
   - \neg B \Rightarrow (\neg T \Rightarrow \neg A) Vrai, si B est vrai, alors le résultat l'est aussi, et on ne nous soucis nullement de la deuxième proposition. Si B faux, alors on s'intéresse, cette fois si, à la deuxième proposition, qui est vrai, donc le résultat l'est aussi.
   - A \Rightarrow (\neg B \Rightarrow (\neg T \Rightarrow \neg A)) Meme raisonnement qu'auparavant. Ainsi le résultat est vrai.



* Les Quantifiers

** Qu'est qu'un quantifier ?

    Prenez la fonction f(x) = x. Cette fonction a 3 particularités majeures :
        - *strictement croissante*
        - *affine*
        - *définie sur R*

    On peut donc déduire certaines propriétés de cette fonction :
        - Pour tous x de R, il existe un et un seul y de R tel que *f(y) = x*
        - Pour tous x de R, il existe au moins un y de R tel que *f(x) < f(y)*

    Soyez sur de comprendre ces propriétés. De comprendre la réfléxion derrière.

    L'outil mathématiques nous donne des outils pour écrire ces propriétés:
        - \forall qui peut se lire comme *pour tout*
        - \exists qui peut se lire comme *il existe au moins*
        - \exists! qui peut se lire comme *il existe un et un seul*

    Ainsi on peut les réecrire comme cela :
        - \forall x \in R \exists! y \in R (f(y) = x)
        - \forall x \in R \exist y \in R (f(x) < f(y))

** Les règles des quantifiers
*** L'orde des quantifiers est important

Ces deux propositions

- \forall n \in N \exists m \in N (n < m)
- \exists m \in N \forall n \in N (n < m)

*N'ont pas du tout la même signification*, le premier peut se lire comme

Pour tous n de N, il existe un m de N strimement supérieur à n. Donc que N est infini, ce qui est parfaitement *vrai*.

Alors que le second

Il existe un n de N strictement supérieur à tous les autres m de N. Donc que N est fini, ce qui est *faux*.

*** La négation des quantifiers

Comme cela reste une proposition, nous pouvons *toujours utiliser* la conjonction, disjonction, implication, équivalence et négation. Cette dernière a une propriété avec les quantifiers.

Prenons le pattern suivant :

    - \forall a \in S, \exists b \in S (P(a,b))

      Avec a,b des variables, S un ensemble quelconque et P une proposition dépendante de deux valeurs.

*Exercice* Quel est sa négation ? (\neg (\forall a \in S, \exists b \in S (P(a,b)))

*Solution* Si cette proposition est fausse, il suffit juste de trouver un contre-exemple. Le contre-exemple aura donc les propriétés "inverses" de notre proposition initiale.

Ainsi, on aura :

    - \exists a \in S, \forall b \in S (\neg P(a,b))

Si cela vous semble confus, traduisez-le littéralement :

    - Pour tous a dans S, il existe au moins un b dans S qui vérifie la proposition suivante : P(a,b); en
    - Il existe un a dans D qui pour tout b dans S vérifie \neg P(a,b)

*** Les quantifiers ne créent pas de proposition

Les quantifiers tel quel ne sont pas des propositions, ainsi quelque chose comme cela :

    - \forall n \in N \land \exists m \in N ; \neg \forall x \in R

est gramaticalement incorrect.


** Exercices

    1) Exprimer la proposition P qui désigne si un nombre est premier ou non.

    2) Dire si ces prochaines propositions sont vraies ou fausses :

      a) \forall x in R, \exists y \in \R ( sqrt{x} = y ) ;; sqrt = racine carré

      b) \exists n \in N+, \forall m \in N- (n > m)

      c) \forall n \in N+, \forall m \in N- (n > m)

    3) Faites la négation de cette proposition :

      - \exists x \in R, \exists y \in R ( y > x > y² \Rightarrow ( 0 < x < 1 \land 0 < y < 1 ) )


*** Solutions

1) P(n) :\equiv n > 1 \land \forall m \in N ((1 < m \land m² \le n) \Rightarrow \neg (m | n)) ou n dénote d'un entier naturel

   ;; m | n -> "m divise n"

   - Simplement, un nombre premier est un entier naturel qui a deux diviseurs : 1 et lui-même.

   - Ainsi on pose n notre entier naturel, avec une condition initiale, il doit être nécessairement plus grand que 1 (1 n'est pas un nombre premier)

   - Ensuite on regarde pour tout entier naturel m, si il est compris entre 2 (2 compris) et m² \le n. Pourquoi cette intervalle ? Et bien essayez d'y répondre par vous-même. Un indice, listez tous les diviseurs d'un entier naturel non premier (comme 48 par exemple)

   - Si c'est le cas on regarde s'il est diviseur de n. Si m divise n, alors n n'est pas premier, sinon tout va bien, n est premier.
     ;; note : les valeurs non comprises dans l'intervalle [2,m² \le 2] ne sont pas des diviseurs de n, donc même si elles sont prises en compte, elles vont être "dépendante" des valeurs de cet intervalle.

2) Exercice 2

   a) Faux, pour les nombres négatifs

   b) Vrai, pour n = 1 par exemple

   c) Vrai aussi

3) \forall x \in R, \forall y \in R ( x > y > x² \land ( 0 \ge x \ge 1 \lor 0 \ge y \ge 1 ))

   (P \Rightarrow Q) \Leftrightarrow (\neg P \lor Q) ainsi

   \neg (P \Rightarrow Q) \Leftrightarrow \neg (\neg P \lor Q) \Leftrightarrow (P \land \neg Q)
