#+TITLE:Introduction
#+AUTHOR: Pim


* Table Of Contents :toc:
- [[#propositions][Propositions]]
  - [[#quest-quune-proposition-][Qu'est qu'une proposition ?]]
  - [[#exemples][Exemples]]
  - [[#subtilités][Subtilités]]
  - [[#les-propositions-composées][Les propositions composées]]
- [[#propositions-avec-symboles][Propositions avec symboles]]
  - [[#conjonction][Conjonction]]
  - [[#disjonction][Disjonction]]
  - [[#implication][Implication]]
  - [[#léquivalence][L'équivalence]]
  - [[#négation][Négation]]
  - [[#exercice-complexe-safépeur][Exercice complexe (safépeur)]]
- [[#les-quantifiers][Les Quantifiers]]
  - [[#quest-quun-quantifier-][Qu'est qu'un quantifier ?]]

* Propositions
** Qu'est qu'une proposition ?

Une proposition est *un objet théorique*, ayant la particularité suivante : *il est soit Vrai, soit Faux*.

** Exemples

- John a 27 ans.

Correcte et simple.

- Il fait beau aujourd'hui.

Correcte et facilement vérifiable.

- 4 > 9
Malgrès une absurdité, cela n'en reste pas moins une proposition. (mais ca pique les yeux quand même).

** Subtilités

- Une proposition qui ne décrit qu'une seule idée (1 = 2 - 1) est dit *atomique*

- Les prochaines phrases, informations *ne sont pas des propositions*:

  + Va t'en.

    N'a pas de sens. Ne donne pas d'idée, c'est juste un ordre. (mais reste quand même hein)

  + x - 3 = 5

    Pas correct, car nous n'avons *pas d'informations sur x*. Il faut lui attribuer une valeur pour que cela devienne une proposition.

  + Cette proposition est fausse.

    Une proposition ne peut pas se *réferrer à elle-même*.

** Les propositions composées

A l'instar des propositions atomiques (une seule idée), les *compositions composées* sont composées de plusieurs sous propositions. Nous avons donc avoir besoin *d'objet nous permettant de lier les propositions entre-elles*. (je les decrirai dans le prochain sujet)

- Exemple:

  *John a 27 ans et il aime les bières*

  Ici 2 idées misent en évidence, et misent en relation avec *et*

* Propositions avec symboles

** Conjonction

Une proposition composée avec une conjonction nécessite que les *2 sous-propositions soit vraies*.
On le note \land .

*** Exemples:

  - (5 > 3) \land (9 < 10)

    Vrai, *car les deux sous-propositions sont vraies*

  - (5 < 3) \land (9 < 10)

    Faux, car 5 < 3 est faux

  - ((5 > 3) \land (9 < 10)) \land John est heureux

    John étant quelqu'un d'heureux, cette proposition est vraie.

*** Sa table de vérité

| A | B | A \land B |
|---+---+-----------|
| 0 | 0 |         0 |
| 0 | 1 |         0 |
| 1 | 0 |         0 |
| 1 | 1 |         1 |

Les *1* représentent une proposition vraie, les *0* des fausses.


** Disjonction

Cette fois-ci, il faut que *au moins une des deux sous-proposition soit vraie*. On la note \lor .

*** Exemples:

  - (5 > 3) \lor (5 < 3)

    Vrai, c'est la première sous-proposition qui prend le dessus.

  - (10 > 15) \lor (8 < 5)

    Faux.

  - ((John est heureux) \lor (John est malheureux)) \lor (2/3 = 3/2)

    Vraie, la puissance de la gaieté de John est absolue !

*** Sa table de vérité

| A | B | A \lor B |
|---+---+----------|
| 0 | 0 |        0 |
| 0 | 1 |        1 |
| 1 | 0 |        1 |
| 1 | 1 |        1 |

** Implication
L'implication peut-être lu comme un *si ... alors*. On la note \Rightarrow .Dans l'expression
*A \Rightarrow B*, si A est vraie, alors le résultat sera *B*, sinon Vraie.

*** Exemples
- (3 < 2) \Rightarrow (5 < 3)

Vrai, car la proposition initiale (le A dans le pattern juste au dessus), est faux, donc le résultat sera vraie.

- (2 = 1 + 1) \Rightarrow (John est triste)

Bien sur, comme John est heureux, le résultat est Faux

*** Sa table de vérité

| A | B | A \Rightarrow B |
|---+---+-----------------|
| 0 | 0 |        1        |
| 0 | 1 |        1        |
| 1 | 0 |        0        |
| 1 | 1 |        1        |



** L'équivalence

Comme son nom l'indique, cela correspond à vérifier si les deux sous-propositions sont équivalentes. On la note \Leftrightarrow

*** Exemples

- ((3 < 5) \land (9 < 5)) \Leftrightarrow ((4 = 8/2) \Rightarrow (3 > 4))

Les *deux sous-propositions étant fausses*, la proposition est donc vraie (si vous avez un doute sur pourquoi ces sous-propositions sont fausses, relisez les paragraphes qui leurs sont dédiés)

- x est positif \Leftrightarrow x est négatif

Les deux sous-propositions étant contraires (on va le voir juste après), il y a donc *nécessairement une des deux qui est fausse, et l'autre vraie* (inutile de connaître x). Ainsi le résultat sera faux.

*** Sa table de vérité

| A | B | A \Leftrightarrow B |
|---+---+---------------------|
| 0 | 0 |                   1 |
| 0 | 1 |                   0 |
| 1 | 0 |                   0 |
| 1 | 1 |                   1 |

** Négation

La négation est assez simple, elle change simplement l'état d'une proposition. On la note \neg


*** Exemples

- \neg ((3 < 4) \Leftrightarrow (4 < 3))

  Vrai, la proposition est fausse initialement, ainsi son état passe à vraie.

- \neg ((100 = 10 * 10) \Rightarrow ((3 \in S) \land (3 \notin S)))

  Vrai aussi


*** Sa table de vérité

| A | \neg A |
|---+--------|
| 0 |      1 |
| 1 |      0 |


** Exercice complexe (safépeur)

Essaye de les faire sans regarder la réponse, mais bon tu fais ce que tu veux.

*** Exercice

Posons T comme étant une proposition à l'état vraie.

Determinez pour chacun des cas suivant, si on peut connaître à coup sur le résultat de la proposition. (Un exemple pour exprimer mon propos)

- Exemple :

  T \land (\neg T)

  Ici, nous pouvons être à coup sur que le résultat sera faux. C'est cette certitude que nous cherchons. Il suffit de dire si elle existe ou non, si oui, donnez sa valeur.

1) T \lor A
2) T \Rightarrow A
3) \neg T \Rightarrow \neg (A \lor B)
4) \neg (\neg T \land A) \Leftrightarrow \neg T
5) \neg ((\neg T \land \neg A) \Leftrightarrow \neg B)
6) A \Rightarrow (\neg B \Rightarrow (\neg T \Rightarrow \neg A))

*** Solutions

1) T étant vrai, pas besoin de savoir l'état de A pour savoir que le résultat est déjà défini, et est vrai.
2) On ne peut pas savoir, la solution dépend de A.
3) On peut le determiner, nous somme dans le cas contraire du précedant, la première proposition étant fausse, le résultat est fini, qu'importe la deuxième. Le résultat est donc vrai.

   (Jusque là c'était juste de la lecture des tables de vérités)

4) Procédons au cas par cas

   - (\neg T \land A) : Faux car \neg T est faux
   - \neg (\neg T \land A) : Vrai, par déduction de l'affirmation précedente
   - \neg (\neg T \land A) \Leftrightarrow \neg T : Faux, car \neg T et Vrai ne sont pas identiques.

5) Procédons au cas par cas

   - (\neg T \land \neg A) : Faux, car \neg T est Faux
   - (\neg T \land \neg A) \Leftrightarrow \neg B) : On ne peut pas savoir, nous ne connaissons rien de B
   - \neg ((\neg T \land \neg A) \Leftrightarrow \neg B) : Ainsi on ne peut pas le déterminer.

6) Procédons au cas par cas

   - \neg T \Rightarrow \neg A Necessairement vrai, \neg T est faux
   - \neg B \Rightarrow (\neg T \Rightarrow \neg A) Vrai, si B est vrai, alors le résultat l'est aussi, et on ne nous soucis nullement de la deuxième proposition. Si B faux, alors on s'intéresse, cette fois si, à la deuxième proposition, qui est vrai, donc le résultat l'est aussi.
   - A \Rightarrow (\neg B \Rightarrow (\neg T \Rightarrow \neg A)) Meme raisonnement qu'auparavant. Ainsi le résultat est vrai.



* Les Quantifiers

** Qu'est qu'un quantifier ?

TODO
